spiceroad/spiceroad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('spicy.urls', namespace='spicy'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

spiceroad/spicy/urls.py
from django.urls import path
from . import views
from .views import (HomeView, ItemDetailView, OrderSummaryView, AddCouponView, CheckoutView)

app_name = 'spicy'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('index', HomeView.as_view(), name='index'),
    path('login', views.user_login, name="user_login"),
    path('register', views.user_register, name="user_register"),
    path('logout', views.user_logout, name='user_logout'),
    path('checkout', CheckoutView.as_view(), name="checkout"),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('cart', OrderSummaryView.as_view(), name="cart"),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),


]

spiceroad/spicy/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse

# Create your models here.
CATEGORY_CHOICES = (
    ("K", "Kitap"),
    ("C", "Çizgi Roman"),
    ("M", "Manga"),
    ("EK", "E-Kitap"),
    ("D", "Dergi"),
)

class Item(models.Model):
    
    title = models.CharField(max_length=100)
    price = models.FloatField()
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    slug = models.SlugField()
    image = models.ImageField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("spicy:product", kwargs={
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("spicy:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("spicy:remove-from-cart", kwargs={
            'slug': self.slug
        })
    
class OrderItem(models.Model):
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
class Order(models.Model):
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE )
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        if self.coupon:
            total -= self.coupon.amount
        return total
    
class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

spiceroad/templates/account.html
{% extends "base.html" %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/footeralt.css' %}">

{% block content %}
    <div class="container mt-5" style="
    display: flex;
    align-items: center;
    justify-content: center;
    height: 72vh;
    ">

        <h2>Hello There</h2>

    </div>
{% endblock %}

spiceroad/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta http-equiv="x-ua-compatible" content="ie=edge" />
      <title>Spicy</title>
      <!-- Font Awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
      <!-- Google Fonts Roboto -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
      <!-- MDB -->
      <link rel="stylesheet" href="static/css/mdb.min.css" />
      <link rel="stylesheet" href="static/css/bootstrap.min.css"  />
      <link rel="stylesheet" href="static/css/style.min.css" />
      <style type="text/css">
        html,
        body,
        header,
        .carousel {
          height: 60vh;
        }
    
        @media (max-width: 740px) {
    
          html,
          body,
          header,
          .carousel {
            height: 100vh;
          }
        }
    
        @media (min-width: 800px) and (max-width: 850px) {
    
          html,
          body,
          header,
          .carousel {
            height: 100vh;
          }
        }
    
      </style>
  </head>

  <body>

    {% include "navbar.html" %}


    {% block content %}{% endblock %}
      
    {% include "footer.html" %}
    {% include "scripts.html" %}
  </body>
</html>

spiceroad/templates/cart.html
{% extends "base.html" %}

{% block content %}



    <main class="mt-5 pt-4">
        <div class="container">

                <div class=" text-nowrap">
                <h2>Cart </h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'spicy:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'spicy:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            ₺{{ order_item.get_total_item_price }}
                            <a style='color: red;' href="{% url 'spicy:remove-from-cart' order_item.item.slug %}">
                            <i class="fas fa-trash float-right"></i>
                        </a>
                        </td>
                    </tr>
                    {%  empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                        <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Coupon</b></td>
                        <td><b>-₺{{ object.coupon.amount }}</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td><b>₺{{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">

                        <a class='btn btn-warning float-right ml-2' href='/checkout'>Proceed to checkout</a>
                        <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>        
                
                </div>
                
        </div>
    </main>

{% endblock content %}

spiceroad/templates/checkout.html
{% extends "base.html" %}

{% block content %}

<main  style="margin-bottom: 3rem;">
  <div class="container">

      <h2 class="my-5 text-center">Checkout form</h2>


      <div class="row">

          <div class="col-md-8 mb-4">
              <!--Card-->
              <div class="card p-4">
                  <!--Grid row-->
                  <div class="row mb-3">
                      <!--Grid column-->
                      <div class="col-md-6 mb-2">
                          <!--firstName-->
                          <div class="form-outline">
                              <input type="text" id="typeText" class="form-control" />
                              <label class="form-label" for="typeText">First name</label>
                          </div>
                      </div>
                      <!--Grid column-->

                      <!--Grid column-->
                      <div class="col-md-6 mb-2">
                          <!--lastName-->
                          <div class="form-outline">
                              <input type="text" id="typeText" class="form-control" />
                              <label class="form-label" for="typeText">Last name</label>
                          </div>
                      </div>
                      <!--Grid column-->
                  </div>
                  <!--Grid row-->

                  <!--Username-->
                  <div class="input-group mb-4">
                      <span class="input-group-text" id="basic-addon1">@</span>
                      <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" />
                  </div>

                  <!--email-->
                  <p class="mb-0">
                      Email (optional)
                  </p>
                  <div class="form-outline mb-4">
                       <input type="email" class="form-control" placeholder="youremail@example.com" aria-label="youremail@example.com" aria-describedby="basic-addon1" />
                  </div>

                  <!--address-->
                  <p class="mb-0">
                      Address
                  </p>
                  <div class="form-outline mb-4">
                      <input type="email" class="form-control" placeholder="1234 Main St" aria-label="1234 Main St" aria-describedby="basic-addon1" />
                  </div>

                  <!--address-2-->
                  <p class="mb-0">
                      Address 2 (optional)
                  </p>
                  <div class="form-outline mb-4">
                      <input type="email" class="form-control" placeholder="Apartment or suite" aria-label="Apartment or suite" aria-describedby="basic-addon1" />
                  </div>

                  <!--Grid row-->
                  <div class="row">
                      <!--Grid column-->
                      <div class="col-lg-4 col-md-12 mb-4">
                          <p class="mb-0">
                              Country
                          </p>
                          <div class="form-outline mb-4">
                      <input type="email" class="form-control" placeholder="United States" aria-label="United States" aria-describedby="basic-addon1" />
                  </div>
                      </div>
                      <!--Grid column-->

                      <!--Grid column-->
                      <div class="col-lg-4 col-md-12 mb-4">
                          <p class="mb-0">
                              State
                          </p>
                          <div class="form-outline mb-4">
                      <input type="email" class="form-control" placeholder="California" aria-label="California" aria-describedby="basic-addon1" />
                  </div>
                      </div>
                      <!--Grid column-->

                      <!--Grid column-->
                      <div class="col-lg-4 col-md-12 mb-4">
                          <p class="mb-0">
                              Zip
                          </p>
                          <div class="form-outline">
                              <input type="text" class="form-control"/>
                          </div>
                      </div>
                      <!--Grid column-->
                  </div>
                  <!--Grid row-->

                  <hr />
                  <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" />
                      <label class="form-check-label" for="flexCheckDefault">Shipping address is the same as my billing address</label>
                  </div>

                  <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" />
                      <label class="form-check-label" for="flexCheckDefault">Save this information for next time</label>
                  </div>

                  <hr />

                  <div class="my-3">
                      <div class="form-check">
                          <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" checked />
                          <label class="form-check-label" for="flexRadioDefault1"> Credit card </label>
                      </div>

                      <div class="form-check">
                          <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" />
                          <label class="form-check-label" for="flexRadioDefault2"> Debit card </label>
                      </div>
                      <div class="form-check">
                          <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3" />
                          <label class="form-check-label" for="flexRadioDefault3"> Paypal </label>
                      </div>
                  </div>
                  <div class="row mb-3">
                      <div class="col-md-6 mb-3">
                          <p class="mb-0">
                              Name on card
                          </p>
                          <div class="form-outline">
                              <input type="text" class="form-control"/>
                              <div class="form-helper">Full name as displayed on card</div>
                          </div>
                      </div>
                      <div class="col-md-6 mb-3">
                          <p class="mb-0">
                              Credit card number
                          </p>
                          <div class="form-outline">
                              <input type="text" class="form-control" />                                
                          </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-3 mb-3">
                          <p class="mb-0">
                              Expiration
                          </p>
                          <div class="form-outline">
                              <input type="text" class="form-control" />
                              
                          </div>
                      </div>
                      <div class="col-md-3 mb-3">
                          <p class="mb-0">
                              CVV
                          </p>
                          <div class="form-outline">
                              <input type="text" class="form-control" />
                              
                          </div>
                      </div>
                  </div>
                  <hr class="mb-4" />                    
                <button class="btn btn-primary" type="button">Continue to checkout</button>
              </div>
              <!--/.Card-->
          </div>

          <div class="col-md-4 mb-4">

              <!-- Cart -->
              <div class="col-md-12 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
                <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
                </h4>
                <ul class="list-group mb-3 z-depth-1">
                {% for order_item in order.items.all %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                    <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                    <small class="text-muted">{{ order_item.item.description}}</small>
                    </div>
                    <span class="text-muted">₺{{ order_item.get_final_price }}</span>
                </li>
                {% endfor %}
                {% if order.coupon %}
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small>{{ order.coupon.code }}</small>
                    </div>
                    <span class="text-success">-₺{{ order.coupon.amount }}</span>
                </li>
                {% endif %}
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total (TL)</span>
                    <strong>₺{{ order.get_total }}</strong>
                </li>
                </ul>
              <!-- Cart -->

              <!-- Promo code -->
              {% if DISPLAY_COUPON_FORM %}
              <form class="card p-2" action="{% url 'spicy:add-coupon' %}" method="POST">
                  {% csrf_token %}
                  <div class="input-group">
                      {{ couponform.code }}
                      <div class="input-group-append">
                      <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                      </div>
                  </div>
              </form>
              {% endif %}
              <!-- Promo code -->
          </div>
          <!--Grid column-->
      </div>
      <!--Grid row-->
  </div>
</main>

{% endblock %}

spiceroad/templates/footer.html
<footer class="text-center text-white mt-4" style="position:static; bottom:0; width: 100% ;background-color: #607D8B">
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); color: #E0E0E0">
      © 2022 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
</footer>

spiceroad/templates/index.html
{% extends "base.html" %}
{% block content %}



  <!--Main layout-->
  <main>
    <div class="container">
          <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
          <!-- Container wrapper -->
          <div class="container-fluid">

            <!-- Navbar brand -->
            <a class="navbar-brand" href="#">Categories:</a>

            <!-- Toggle button -->
            <button 
              class="navbar-toggler" 
              type="button" 
              data-mdb-toggle="collapse" 
              data-mdb-target="#navbarSupportedContent2" 
              aria-controls="navbarSupportedContent2" 
              aria-expanded="false" 
              aria-label="Toggle navigation">
              <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent2">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <!-- Link -->
                <li class="nav-item acitve">
                  <a class="nav-link text-white" href="#">All</a>
                </li>
                <li class="nav-item">
                      <a class="nav-link text-white" href="#">Kitap</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="#">Çizgi Roman</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="#">Manga</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="#">E-Kitap</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="#">Dergi</a>
                    </li>

              </ul>

              <!-- Search -->
              <form class="w-auto py-1" style="max-width: 12rem">
                <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
              </form> 



            </div>
          </div>
          <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
      
    <!-- Products -->
        <section>
          <div class="text-center">
            <div class="row wow fadeIn">

              {% for item in object_list %}
              <div class="col-lg-3 col-md-6 mb-4">
                <div class="card">
                  <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                    data-mdb-ripple-color="light">
                    <img src="{{ item.image.url }}" class="card-img-top" style="width: 255px; height: 350px;">
                    <a href="{{ item.get_absolute_url }}">
                      <div class="hover-overlay">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                      </div>
                    </a>
                  </div>
                  <div class="card-body">
                    <a href="" class="text-reset">
                      <h5 class="card-title mb-2">{{ item.title }} </h5>
                    </a>
                    <a href="" class="text-reset ">
                      <p>{{ item.get_category_display }}</p>
                    </a>
                    <h6 class="mb-3 price">{{ item.price }}₺</h6>
                  </div>
                </div>
              </div>
              {% endfor %}


          </div>
      </section>
      
      <!-- Pagination -->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

spiceroad/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<main class="mt-1 pt-1">
    <div class="container mt-5" style="    
    display: flex;
    align-items: center;
    justify-content: center;
    height: 72vh;">
        <form action="{% url 'spicy:user_login' %}" method="post">
            {% csrf_token %}
            <div class="">
                <div class="" style="
                width: 300px;
                height: 250px;
                padding: 20px;
                border: 1px solid #ccc;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">

                    <div>
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <div style="margin-bottom: 5px;">
                            <div class="">
                                <label for="username" class="">Username:</label>
                                <div class="">
                                    <input name="username" value="" type="text" class="form-control" />
                                </div>
                            </div>
                            <div class="">
                                <label for="password" class="">Password:</label>
                                <div class="">
                                    <input name="password" type="password" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="" style="margin-top: 30px;">
                            <input name="login" type="submit" value="Login" class="btn btn-success" /> &nbsp;
                            <a href="">Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</main>
{% endblock %}

spiceroad/templates/product.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mdb.min.css' %}">



<main class="mt-5 pt-4">
        <div class="container mt-5">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-md-6 mb-4">
                    <img src="{{ item.image.url }}" class="card-img-top" style="width: 255px; height: 350px; margin-left: 250px;">
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">
                    <!--Content-->
                    <div class="p-4">
                        <div class="mb-3">
                            <a href="">
                                <span class="badge bg-dark me-1">{{ item.get_category_display}}</span>
                            </a>

                        </div>

                        <p class="lead">
                            <span>${{ item.price }}</span>
                        </p>

                        <strong><p style="font-size: 20px;">Description</p></strong>

                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa sint voluptatibus! Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>

                        <form class="d-flex justify-content-left">
                            <!-- Default input -->
                            <div class="form-outline me-1" style="width: 100px;">
                                <input type="number" value="1" class="form-control" />
                            </div>
                            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                                Add to cart
                                <i class="fas fa-shopping-cart ml-1"></i>
                            </a>
                            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                                Remove from cart
                            </a>
                        </form>
                    </div>
                    <!--Content-->
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->

            <hr />

            <!--Grid row-->
            <div class="row d-flex justify-content-center">
                <!--Grid column-->
                <div class="col-md-6 text-center">
                    <h4 class="my-4 h4">Additional information</h4>

                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->

            <!--Grid row-->

            <!--Grid row-->
        </div>
</main>

{% endblock %}

spiceroad/templates/register.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="container mt-5" style="
    display: flex;
    align-items: center;
    justify-content: center;
    height: 72vh;">
        <form action="{% url 'spicy:user_register' %}" method="post">
            {% csrf_token %}
            <div style="
            width: 300px;
            height: 350px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 8px;
            margin-top: 50px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"
            >
                <div>

                    <div>
                        {% if error_message %}
                            <p>{{ error_message }}</p>
                        {% endif %}
                       <div style="margin-bottom: 5px;">
                            <div>
                                <label for="{{ form.username.id_for_label }}">Username</label>
                                <div>
                                    {{ form.username }}
                                </div>
                            </div>
                            <div>
                                <label for="{{ form.email.id_for_label }}">Email</label>
                                <div>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div>
                                <label for="{{ form.password.id_for_label }}">Password</label>
                                <div>
                                    {{ form.password }}
                                </div>
                            </div>
                            <div>
                                <label for="{{ form.password_repeat.id_for_label }}">Confirm password:</label>
                                <div>
                                    {{ form.password_repeat }}
                                </div>
                            </div>
                        </div>
                        <div style="margin-top: 30px;">
                            <input type="submit" value="Register" class="btn btn-success">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}